declare module 'tulind' {
  export type IndicatorFn = (inputs: number[], options: number[], cb: (err: any, results: number[]) => void) => void

  export interface Indicators {
    abs: { indicator: IndicatorFn }
    acos: { indicator: IndicatorFn }
    ad: { indicator: IndicatorFn }
    add: { indicator: IndicatorFn }
    adosc: { indicator: IndicatorFn }
    adx: { indicator: IndicatorFn }
    adxr: { indicator: IndicatorFn }
    ao: { indicator: IndicatorFn }
    apo: { indicator: IndicatorFn }
    aroon: { indicator: IndicatorFn }
    aroonosc: { indicator: IndicatorFn }
    asin: { indicator: IndicatorFn }
    atan: { indicator: IndicatorFn }
    atr: { indicator: IndicatorFn }
    avgprice: { indicator: IndicatorFn }
    bbands: { indicator: IndicatorFn }
    bop: { indicator: IndicatorFn }
    cci: { indicator: IndicatorFn }
    ceil: { indicator: IndicatorFn }
    cmo: { indicator: IndicatorFn }
    cos: { indicator: IndicatorFn }
    cosh: { indicator: IndicatorFn }
    crossany: { indicator: IndicatorFn }
    crossover: { indicator: IndicatorFn }
    cvi: { indicator: IndicatorFn }
    decay: { indicator: IndicatorFn }
    dema: { indicator: IndicatorFn }
    di: { indicator: IndicatorFn }
    div: { indicator: IndicatorFn }
    dm: { indicator: IndicatorFn }
    dpo: { indicator: IndicatorFn }
    dx: { indicator: IndicatorFn }
    edecay: { indicator: IndicatorFn }
    ema: { indicator: IndicatorFn }
    emv: { indicator: IndicatorFn }
    exp: { indicator: IndicatorFn }
    fisher: { indicator: IndicatorFn }
    floor: { indicator: IndicatorFn }
    fosc: { indicator: IndicatorFn }
    hma: { indicator: IndicatorFn }
    kama: { indicator: IndicatorFn }
    kvo: { indicator: IndicatorFn }
    lag: { indicator: IndicatorFn }
    linreg: { indicator: IndicatorFn }
    linregintercept: { indicator: IndicatorFn }
    linregslope: { indicator: IndicatorFn }
    ln: { indicator: IndicatorFn }
    log10: { indicator: IndicatorFn }
    macd: { indicator: IndicatorFn }
    marketfi: { indicator: IndicatorFn }
    mass: { indicator: IndicatorFn }
    max: { indicator: IndicatorFn }
    md: { indicator: IndicatorFn }
    medprice: { indicator: IndicatorFn }
    mfi: { indicator: IndicatorFn }
    min: { indicator: IndicatorFn }
    mom: { indicator: IndicatorFn }
    msw: { indicator: IndicatorFn }
    mul: { indicator: IndicatorFn }
    natr: { indicator: IndicatorFn }
    nvi: { indicator: IndicatorFn }
    obv: { indicator: IndicatorFn }
    ppo: { indicator: IndicatorFn }
    psar: { indicator: IndicatorFn }
    pvi: { indicator: IndicatorFn }
    qstick: { indicator: IndicatorFn }
    roc: { indicator: IndicatorFn }
    rocr: { indicator: IndicatorFn }
    round: { indicator: IndicatorFn }
    rsi: { indicator: IndicatorFn }
    sin: { indicator: IndicatorFn }
    sinh: { indicator: IndicatorFn }
    sma: { indicator: IndicatorFn }
    sqrt: { indicator: IndicatorFn }
    stddev: { indicator: IndicatorFn }
    stderr: { indicator: IndicatorFn }
    stoch: { indicator: IndicatorFn }
    sub: { indicator: IndicatorFn }
    sum: { indicator: IndicatorFn }
    tan: { indicator: IndicatorFn }
    tanh: { indicator: IndicatorFn }
    tema: { indicator: IndicatorFn }
    todeg: { indicator: IndicatorFn }
    torad: { indicator: IndicatorFn }
    tr: { indicator: IndicatorFn }
    trima: { indicator: IndicatorFn }
    trix: { indicator: IndicatorFn }
    trunc: { indicator: IndicatorFn }
    tsf: { indicator: IndicatorFn }
    typprice: { indicator: IndicatorFn }
    ultosc: { indicator: IndicatorFn }
    var: { indicator: IndicatorFn }
    vhf: { indicator: IndicatorFn }
    vidya: { indicator: IndicatorFn }
    volatility: { indicator: IndicatorFn }
    vosc: { indicator: IndicatorFn }
    vwma: { indicator: IndicatorFn }
    wad: { indicator: IndicatorFn }
    wcprice: { indicator: IndicatorFn }
    wilders: { indicator: IndicatorFn }
    willr: { indicator: IndicatorFn }
    wma: { indicator: IndicatorFn }
    zlema: { indicator: IndicatorFn }
  }

  export var indicators: Indicators
}
